### ISSUE TITLE
Predlog: Github Template

### ISSUE THREAD

**Issue by Blarc** [RoboLiga/ev3-nabiralec#2]
Ta repozitorij bi lahko spremenili v Github Template, ki ti omogoča da z enim klikom narediš nov repozitorij v svojem Github profilu, ki vsebuje vse kar vsebuje tudi ta repozitorij. 

Stvar je zelo preprosta, potrebno je zgolj vklopiti v nastavitvah: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository.

**Comment by nejci** [comment]
Odlična ideja, bom.
